version: '3.8'

services:
  python-api1:
    build:
      context: ./face-recognition-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 

  python-api2:
    build:
      context: ./login-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
